/*
Auto-generated by gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export function Astronaut(props) {

  const group = useRef();

  const { nodes, materials, animations } =
    useGLTF("/models/tenhun_falling_spaceman_fanart.glb");

  const { actions } = useAnimations(
    animations,
    group
  );

  // play rig animation
  useEffect(() => {
    if (animations && animations.length > 0) {
      const action =
        actions[animations[0].name];
      action && action.play();
    }
  }, [actions, animations]);

  // ---------- FALL STATE ----------

  const [fallDone, setFallDone] =
    useState(false);

  const fallY = useRef(5); // start high

  useFrame((state, delta) => {

    if (!group.current) return;

    // ---------- FALL ----------

    if (!fallDone) {

      fallY.current -= delta * 2; // speed

      if (fallY.current <=
          (props.position?.[1] ?? -1)
      ) {

        fallY.current =
          props.position?.[1] ?? -1;

        setFallDone(true);

      }

      group.current.position.y =
        fallY.current;

    }

    // ---------- FLOAT ----------

    else {

      group.current.position.y =
        (props.position?.[1] ?? -1) +
        Math.sin(
          state.clock.elapsedTime
        ) * 0.3;

      // group.current.rotation.z +=
      //   0.002;

      // group.current.rotation.y +=
      //   0.001;

    }

  });

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      rotation={[-Math.PI / 2, -0.2, 2.2]}
      scale={props.scale || 0.3}
      position={props.position || [1.3, -1, 0]}
    >

      <primitive
        object={nodes.metarig_rootJoint}
      />

      <skinnedMesh
        geometry={nodes.Cube001_0.geometry}
        material={materials["AstronautFallingTexture.png"]}
        skeleton={nodes.Cube001_0.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Cube005_0.geometry}
        material={materials["AstronautFallingTexture.png"]}
        skeleton={nodes.Cube005_0.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Cube002_0.geometry}
        material={materials["AstronautFallingTexture.png"]}
        skeleton={nodes.Cube002_0.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Plane_0.geometry}
        material={materials["AstronautFallingTexture.png"]}
        skeleton={nodes.Plane_0.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Cube008_0.geometry}
        material={materials["AstronautFallingTexture.png"]}
        skeleton={nodes.Cube008_0.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Cube004_0.geometry}
        material={materials["AstronautFallingTexture.png"]}
        skeleton={nodes.Cube004_0.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Cube003_0.geometry}
        material={materials["AstronautFallingTexture.png"]}
        skeleton={nodes.Cube003_0.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Cube_0.geometry}
        material={materials["AstronautFallingTexture.png"]}
        skeleton={nodes.Cube_0.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Cube009_0.geometry}
        material={materials["AstronautFallingTexture.png"]}
        skeleton={nodes.Cube009_0.skeleton}
      />

      <skinnedMesh
        geometry={nodes.Cube011_0.geometry}
        material={materials["AstronautFallingTexture.png"]}
        skeleton={nodes.Cube011_0.skeleton}
      />

    </group>
  );
}

useGLTF.preload(
  "/models/tenhun_falling_spaceman_fanart.glb"
);